### ISSUE TITLE
[FEATURE] Better cmd prompt

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/scp-terminal#12]
Instead of having the prompt be `root@user`, make it load a random name and scp site

**Comment by Gravy59** [comment]
I may attempt to work on this

**Comment by Gravy59** [comment]
Update: I got it working with a static array of names and numbers to choose from. Updating my draft PR.

**Comment by Gravy59** [comment]
I have failed.

**Comment by mellobacon** [comment]
Closing for now since I've implemented a random name thing. For the site I'm just keeping it as site-19 for now until I get proper logins going. In the future there will be a way to set a custom name and site if preferred.
