### ISSUE TITLE
[Bug] Version 0.0.2.0 registers as Version 0.0.1.0

### ISSUE THREAD

**Issue by OfficialEsco** [mellobacon/scp-terminal#16]
**Describe the bug**
Just got a package request to add this app to winget https://github.com/microsoft/winget-pkgs/pull/38012, and i noticed the program registers as version 0.0.1.0 in the `A`dd or `R`emove `P`rograms table instead of 0.0.2.0

**To Reproduce**
Download and install version 0.0.2.0
Open Add or Remove Programs

**Expected behavior**
To appear as 0.0.2.0

**Screenshots**
![image](https://user-images.githubusercontent.com/15158490/146465254-aa37631d-1ef7-46a3-a906-6b9ad3868096.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
The installer needs to update the DisplayVersion registry string
![image](https://user-images.githubusercontent.com/15158490/146465463-0936b524-7d9b-4858-b193-40d79be79781.png)

edit:
Huh, so i guess its the same installer?

> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> - `InstallerSha256: 069da9348420baf491400e2f46b293b5f5d615ca6f3cdddcb79b86566c7d52ab`
>   - manifests\m\mellobacon\scpterminal\0.0.1.0
> 
> _Originally posted by @wingetbot in https://github.com/microsoft/winget-pkgs/issues/38012#issuecomment-996287942_

**Comment by mellobacon** [comment]
Ah whoops. Thanks for the heads up. I just forgot to increment the version number properly. It should be fixed by the next update.
